import listingSections from './listingSections.json'

const SECTION_ICONS = {
  'For Sale': '\u{1F3F7}\uFE0F',
  Housing: '\u{1F3E0}',
  Services: '\u{1F527}',
  Jobs: '\u{1F4BC}',
  Community: '\u{1F91D}'
}

export const SECTIONS = Object.fromEntries(
  Object.entries(listingSections).map(([sectionName, categories]) => [
    sectionName,
    {
      icon: SECTION_ICONS[sectionName] || '',
      categories: Object.entries(categories).map(([name, fields]) => ({ name, fields }))
    }
  ])
)

export const FIELD_LABELS = {
  year: 'Year', make: 'Make', model: 'Model', color: 'Color',
  condition: 'Condition', mileage: 'Mileage', price: 'Price ($)',
  description: 'Description', city: 'City', phone: 'Phone Number',
  yearBuilt: 'Year Built', makeModel: 'Make/Model', type: 'Type',
  title: 'Title', author: 'Author', subject: 'Subject',
  edition: 'Edition', isbn: 'ISBN', item: 'Item', material: 'Material',
  dimensions: 'Dimensions', brand: 'Brand', bedrooms: 'Bedrooms',
  bathrooms: 'Bathrooms', sqft: 'Square Feet', rent: 'Rent ($)',
  deposit: 'Deposit ($)', petsAllowed: 'Pets Allowed', available: 'Available',
  garage: 'Garage', roomType: 'Room Type', furnished: 'Furnished',
  utilities: 'Utilities Included', preferences: 'Preferences',
  zoning: 'Zoning', parking: 'Parking', acres: 'Acres',
  access: 'Road Access', survey: 'Survey Available',
  serviceType: 'Service Type', experience: 'Experience',
  certifications: 'Certifications', rate: 'Rate', availability: 'Availability',
  mobile: 'Mobile Service', residential: 'Residential', commercial: 'Commercial',
  frequency: 'Frequency', supplies: 'Supplies Included', level: 'Level',
  online: 'Online', inPerson: 'In Person', equipment: 'Equipment',
  licensed: 'Licensed', insured: 'Insured', remote: 'Remote',
  onSite: 'On-Site', company: 'Company', industry: 'Industry',
  salary: 'Salary', education: 'Education Required', benefits: 'Benefits',
  hours: 'Hours/Week', pay: 'Pay', schedule: 'Schedule',
  duration: 'Duration', paid: 'Paid', credit: 'College Credit',
  major: 'Relevant Major', skills: 'Skills Required', eventName: 'Event Name',
  date: 'Date', time: 'Time', venue: 'Venue', cost: 'Cost',
  capacity: 'Capacity', organizer: 'Organizer', instructor: 'Instructor',
  materials: 'Materials', organization: 'Organization', role: 'Role',
  commitment: 'Time Commitment', cause: 'Cause/Mission',
  groupName: 'Group Name', meetingTime: 'Meeting Time', location: 'Location',
  size: 'Group Size', requirements: 'Requirements', itemType: 'Item Type',
  reward: 'Reward Offered', contact: 'Contact'
}

export const TEXTAREA_FIELDS = ['description', 'benefits', 'preferences', 'requirements', 'cause']
export const BOOL_FIELDS = ['petsAllowed', 'furnished', 'mobile', 'residential', 'commercial', 'online', 'inPerson', 'licensed', 'insured', 'remote', 'onSite', 'paid', 'credit', 'survey']

export const styles = {
  page: { minHeight: '100vh', background: '#f7f7f5', fontFamily: "'Georgia', serif" },
  header: { background: '#fff', borderBottom: '2px solid #222', position: 'sticky', top: 0, zIndex: 100 },
  headerTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '12px 24px', borderBottom: '1px solid #eee' },
  logo: { display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer' },
  logoIcon: { fontSize: '28px' },
  logoTitle: { fontSize: '20px', fontWeight: 'bold', color: '#222', letterSpacing: '-0.5px' },
  logoSub: { fontSize: '11px', color: '#888', letterSpacing: '1px', textTransform: 'uppercase' },
  headerActions: { display: 'flex', alignItems: 'center', gap: '10px' },
  userBadge: { fontSize: '13px', color: '#555', background: '#f0f0f0', padding: '4px 10px', borderRadius: '20px' },
  visitorBadge: { fontSize: '12px', color: '#888', fontStyle: 'italic' },
  sectionNav: { display: 'flex', gap: '0', overflowX: 'auto', padding: '0 16px' },
  sectionBtn: { padding: '10px 18px', border: 'none', background: 'transparent', cursor: 'pointer', fontSize: '14px', fontWeight: '500', color: '#444', borderBottom: '3px solid transparent', whiteSpace: 'nowrap' },
  sectionBtnActive: { color: '#c00', borderBottom: '3px solid #c00', background: '#fff8f8' },
  container: { maxWidth: '1100px', margin: '0 auto', padding: '24px 16px' },
  breadcrumb: { display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '20px', fontSize: '13px' },
  breadcrumbItem: { color: '#c00', cursor: 'pointer', textDecoration: 'underline' },
  breadcrumbSep: { color: '#aaa' },
  searchRow: { marginBottom: '20px', display: 'flex', gap: '10px' },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))', gap: '16px' },
  card: { background: '#fff', border: '1px solid #ddd', borderRadius: '4px', overflow: 'hidden', cursor: 'pointer' },
  cardImage: { height: '160px', background: '#f0f0f0', overflow: 'hidden' },
  cardImg: { width: '100%', height: '100%', objectFit: 'cover' },
  cardNoImage: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', color: '#bbb', fontSize: '13px' },
  cardBody: { padding: '12px' },
  cardMeta: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '6px' },
  cardCategory: { fontSize: '11px', background: '#fff0f0', color: '#c00', padding: '2px 7px', borderRadius: '3px', fontWeight: '600' },
  cardCity: { fontSize: '11px', color: '#888' },
  cardTitle: { margin: '0 0 4px', fontSize: '15px', fontWeight: '600', color: '#222' },
  cardPrice: { margin: '0 0 6px', fontSize: '16px', fontWeight: 'bold', color: '#c00' },
  cardDesc: { margin: 0, fontSize: '12px', color: '#666', overflow: 'hidden', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical' },
  categoryLanding: { marginBottom: '24px' },
  sectionTitle: { fontSize: '24px', fontWeight: 'bold', marginBottom: '16px', color: '#222' },
  categoryLandingGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '12px' },
  categoryLandingBtn: { background: '#fff', border: '1px solid #ddd', borderRadius: '4px', padding: '16px', cursor: 'pointer', textAlign: 'left' },
  categoryLandingName: { display: 'block', fontSize: '15px', fontWeight: '600', color: '#222', marginBottom: '4px' },
  categoryLandingCount: { fontSize: '12px', color: '#888' },
  homeSections: { marginTop: '8px' },
  homeTitle: { fontSize: '20px', fontWeight: 'bold', marginBottom: '16px', color: '#222', borderBottom: '1px solid #ddd', paddingBottom: '8px' },
  homeSectionGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '16px' },
  homeSectionCard: { background: '#fff', border: '1px solid #ddd', borderRadius: '4px', overflow: 'hidden' },
  homeSectionHeader: { display: 'flex', alignItems: 'center', gap: '8px', padding: '12px 16px', borderBottom: '1px solid #eee', cursor: 'pointer', background: '#fafafa' },
  homeSectionName: { fontSize: '15px', fontWeight: '700', color: '#222' },
  homeCategoryList: { listStyle: 'none', margin: 0, padding: '8px 0' },
  homeCategoryItem: { display: 'flex', justifyContent: 'space-between', padding: '6px 16px', fontSize: '13px', color: '#c00', cursor: 'pointer', textDecoration: 'underline' },
  homeCategoryCount: { color: '#aaa', textDecoration: 'none', fontSize: '11px' },
  modalOverlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 1000, padding: '20px' },
  modal: { background: '#fff', borderRadius: '6px', padding: '28px', width: '100%', boxShadow: '0 4px 20px rgba(0,0,0,0.2)', position: 'relative' },
  closeBtn: { position: 'absolute', top: '12px', right: '16px', background: 'none', border: 'none', fontSize: '18px', cursor: 'pointer', color: '#888' },
  modalTitle: { margin: '0 0 16px', fontSize: '20px', fontWeight: 'bold' },
  stepLabel: { fontSize: '14px', color: '#666', marginBottom: '16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  sectionHeader: { fontSize: '13px', fontWeight: '700', color: '#888', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '8px' },
  categoryGrid: { display: 'flex', flexWrap: 'wrap', gap: '8px', marginBottom: '8px' },
  categoryBtn: { padding: '6px 12px', border: '1px solid #ddd', borderRadius: '3px', background: '#fff', cursor: 'pointer', fontSize: '13px', color: '#333' },
  categoryBtnActive: { background: '#c00', color: '#fff', borderColor: '#c00' },
  formGroup: { marginBottom: '14px' },
  label: { display: 'block', marginBottom: '5px', fontSize: '13px', fontWeight: '600', color: '#444' },
  input: { width: '100%', padding: '8px 10px', border: '1px solid #ccc', borderRadius: '4px', fontSize: '14px', boxSizing: 'border-box', fontFamily: 'inherit' },
  backBtn: { background: 'none', border: 'none', color: '#c00', cursor: 'pointer', fontSize: '13px', textDecoration: 'underline' },
  btnPrimary: { background: '#c00', color: '#fff', border: 'none', padding: '10px 20px', borderRadius: '4px', cursor: 'pointer', fontSize: '14px', fontWeight: '600' },
  btnPost: { background: '#c00', color: '#fff', border: 'none', padding: '8px 16px', borderRadius: '4px', cursor: 'pointer', fontSize: '13px', fontWeight: '600' },
  btnSignOut: { background: 'transparent', color: '#666', border: '1px solid #ccc', padding: '7px 14px', borderRadius: '4px', cursor: 'pointer', fontSize: '13px' },
  detailGrid: { display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '12px' },
  detailRow: { display: 'flex', justifyContent: 'space-between', borderBottom: '1px solid #f0f0f0', paddingBottom: '6px', fontSize: '14px' },
  detailLabel: { color: '#888', fontWeight: '500' },
  detailValue: { color: '#222', textAlign: 'right', maxWidth: '60%' },
  status: { textAlign: 'center', color: '#888', padding: '40px 0' },
  emptyState: { textAlign: 'center', padding: '60px 0', color: '#888' },
  error: { color: '#c00', fontSize: '13px', marginBottom: '12px', background: '#fff0f0', padding: '8px', borderRadius: '4px' }
}
